# Generated by Django 4.1.1 on 2022-09-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_alter_classroom_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
